/**
 * One-time import of DNS records that predate Terraform.
 *
 * Generated by scripts/cloudflare-import.sh against zone yisakmesifin.org.
 * DELETE THIS FILE once the apply has succeeded -- an import block is an
 * instruction to adopt an existing object, not a description of desired
 * state, and it has no meaning after the first apply.
 */

# api.yisakmesifin.org -> 35.153.122.186 (proxied: true)
import {
  to = module.cloudflare[0].cloudflare_dns_record.api
  id = "8166779c73d66db7491dc1c63849cf61/6b6d8045ff06e9d0bd3fd35b05618e19"
}

# rt.yisakmesifin.org -> 35.153.122.186 (proxied: true)
import {
  to = module.cloudflare[0].cloudflare_dns_record.realtime
  id = "8166779c73d66db7491dc1c63849cf61/1dc997d670a74b327660cee58379851d"
}

