#!/usr/bin/env bash
#
# Emit Terraform `import` blocks for DNS records that already exist.
#
# WHY THIS IS NEEDED
#
# api.<domain> and rt.<domain> are already live and proxied. Applying
# modules/cloudflare without importing them would not fail -- and that is the
# problem. Cloudflare permits several A records on one name (round-robin), so
# Terraform would happily CREATE A SECOND record alongside each existing one.
#
# The site would keep working, because both point at the same origin. But
# Terraform would be managing a record nobody uses while the real one stayed
# editable in the dashboard, unmanaged and invisible to every future plan. A
# clean plan that describes the wrong object is worse than no plan.
#
# So: import first, then apply.
#
# Usage:
#   CLOUDFLARE_API_TOKEN=... CLOUDFLARE_ZONE_ID=... DOMAIN_NAME=yisakmesifin.org \
#     ./scripts/cloudflare-import.sh dev
#
# Paste the output into infra/environments/<env>/cloudflare-imports.tf, run the
# apply, then DELETE that file -- import blocks are a one-time instruction, not
# permanent configuration, and leaving them in makes every later plan re-check
# an import that already happened.
#
# Read-only against Cloudflare. It creates and changes nothing.

set -euo pipefail

ENVIRONMENT="${1:-dev}"

: "${CLOUDFLARE_API_TOKEN:?CLOUDFLARE_API_TOKEN is required}"
: "${CLOUDFLARE_ZONE_ID:?CLOUDFLARE_ZONE_ID is required}"
: "${DOMAIN_NAME:?DOMAIN_NAME is required}"

API="https://api.cloudflare.com/client/v4"

GREEN=$'\033[0;32m'; RED=$'\033[0;31m'; YELLOW=$'\033[0;33m'; BOLD=$'\033[1m'; NC=$'\033[0m'
info() { echo "${GREEN}==>${NC} $*" >&2; }
warn() { echo "${YELLOW}==>${NC} $*" >&2; }
die()  { echo "${RED}ERROR:${NC} $*" >&2; exit 1; }

command -v curl >/dev/null 2>&1 || die "curl not found"
command -v jq   >/dev/null 2>&1 || die "jq not found"

cf() {
  curl -fsS -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
       -H "Content-Type: application/json" "${API}$1"
}

# Fail early and clearly if the token cannot even read the zone, rather than
# emitting empty import blocks that fail confusingly at apply time.
ZONE_NAME="$(cf "/zones/${CLOUDFLARE_ZONE_ID}" | jq -r '.result.name // empty')" \
  || die "Could not read zone ${CLOUDFLARE_ZONE_ID}. Does the token have Zone:Read on it?"
[ -n "$ZONE_NAME" ] || die "Zone ${CLOUDFLARE_ZONE_ID} returned no name."

info "Zone: ${ZONE_NAME} (${CLOUDFLARE_ZONE_ID})"

emitted=0
missing=0

echo "/**"
echo " * One-time import of DNS records that predate Terraform."
echo " *"
echo " * Generated by scripts/cloudflare-import.sh against zone ${ZONE_NAME}."
echo " * DELETE THIS FILE once the apply has succeeded -- an import block is an"
echo " * instruction to adopt an existing object, not a description of desired"
echo " * state, and it has no meaning after the first apply."
echo " */"
echo

for pair in "api:api" "realtime:rt"; do
  resource="${pair%%:*}"
  host_prefix="${pair##*:}"
  host="${host_prefix}.${DOMAIN_NAME}"

  records="$(cf "/zones/${CLOUDFLARE_ZONE_ID}/dns_records?name=${host}&type=A")"
  count="$(echo "$records" | jq '.result | length')"

  if [ "$count" -eq 0 ]; then
    warn "${host}: no A record found -- Terraform will CREATE it, which is correct"
    missing=$((missing + 1))
    continue
  fi

  if [ "$count" -gt 1 ]; then
    warn "${host}: ${count} A records already exist. Importing only the first."
    warn "  Resolve the duplicates by hand before applying, or Terraform will"
    warn "  manage one and silently leave the others in place."
  fi

  record_id="$(echo "$records" | jq -r '.result[0].id')"
  proxied="$(echo "$records" | jq -r '.result[0].proxied')"
  content="$(echo "$records" | jq -r '.result[0].content')"

  if [ "$proxied" != "true" ]; then
    warn "${host} is DNS-only. The origin security group admits Cloudflare ranges"
    warn "  only, so this record currently black-holes. Applying will fix it."
  fi

  echo "# ${host} -> ${content} (proxied: ${proxied})"
  echo "import {"
  echo "  to = module.cloudflare[0].cloudflare_dns_record.${resource}"
  echo "  id = \"${CLOUDFLARE_ZONE_ID}/${record_id}\""
  echo "}"
  echo
  emitted=$((emitted + 1))
done

# Zone settings need no import: cloudflare_zone_setting reads the current value
# and updates it, because a setting always exists. Only records, which are
# created objects, can be duplicated.
info "${emitted} import block(s) emitted, ${missing} record(s) left for Terraform to create"

if [ "$emitted" -eq 0 ]; then
  info "Nothing to import. Apply directly."
fi
